### ISSUE TITLE
maxSize not set

### ISSUE THREAD

**Issue by joebalancio** [mio/mongo#2]
I set maxSize as a static property on a resource, but I still get the default 25 items when querying a collection.

**Comment by jontewks** [comment]
Looks like on line 1069 of mio-mongo.js the limit number is set by the query's parameter 'size', not 'maxSize'. Could that be the issue?

**Comment by alexmingoia** [comment]
This is fixed in `mio@1.1.0`. Options are now `maxPageSize` and `defaultPageSize`.
